# Generated by Django 4.2.8 on 2023-12-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scripts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=255)),
                ('paragraph1', models.CharField(max_length=40000)),
                ('paragraph2', models.CharField(max_length=2000)),
                ('paragraph3', models.CharField(max_length=40000)),
                ('paragraph4', models.CharField(max_length=40000)),
                ('paragraph5', models.CharField(max_length=40000)),
            ],
        ),
    ]
