# Generated by Django 4.2.8 on 2024-01-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScriptStudio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scripts',
            name='scripts_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
